repos:
  - repo: 'https://github.com/pre-commit/mirrors-prettier'
    rev: ''
    hooks:
      - id: prettier
  - repo: 'https://github.com/pre-commit/mirrors-eslint'
    rev: ''
    hooks:
      - id: eslint
