repos:
  - repo: 'https://github.com/pre-commit/mirrors-prettier'
    rev: 'v2.6.0'
    hooks:
      - id: prettier
        files: .*\.(ts|tsx|js|jsx|css|json|md|yml)$
  - repo: 'https://github.com/pre-commit/mirrors-eslint'
    rev: 'v8.0.1'
    hooks:
      - id: eslint
        files: \.[t]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin@5.14.0'
          - '@typescript-eslint/parser@5.14.0'
          - prettier@^2.6.0
          - eslint-config-prettier@8.5.0
          - eslint-plugin-prettier@4.0.0
          - typescript@4.1.3
          - eslint@^8.0.0
