#!/usr/bin/env bash
set -eux

# Install the labextension
jlpm run bootstrap
pip install -e . --ignore-installed --no-deps -vv
jupyter labextension develop . --overwrite

# List extensions
jupyter labextension list
